# Generated by Django 2.1.1 on 2018-09-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('spent_on', models.TextField()),
            ],
        ),
    ]
